### ISSUE TITLE
Suggestion: Hovering over a group member should provide info on all members

### ISSUE THREAD

**Issue by armish** [pnavarrc/evsrc-visualization#1]
The current way you hide filenames by default seems to be working great and helping a lot with the overall view for a result set. I also liked the idea of showing filenames when you mouse over a node -- much more convenient. 

Having said this, I think it is rather hard to investigate a coupled file set (strongly connected components of the graph) as you have to mouse over all individual members and have to memorize a few names if you have more than 2 members in a single group. I suggest you either show the names of all members within a group when you mouse over any of these members (might be messy) or list all files in the group in a single pop up when you mouse over any of the individuals.

Looks really amazing!

**Comment by pnavarrc** [comment]
Thanks for the suggestion, I will investigate on how to implement that or another way to visualize the group. Displaying the names of the neighbor nodes should be fairly easy, displaying all the nodes in a group whould involve walking the subgraph and finding the minimum spanning tree or something equivalent.

**Comment by bieron** [comment]
Dumb way of achieving this: https://github.com/pnavarrc/evsrc-visualization/pull/2

**Comment by pnavarrc** [comment]
Thanks to @bieron’s awesome pull request we have color-coded information of all the nodes in a cluster

![image](https://cloud.githubusercontent.com/assets/114084/10445196/5362ffb4-7124-11e5-82de-6cfed9edc466.png)

Available in the [live version](http://pnavarrc.github.io/evsrc-visualization/dist/) as well.

**Comment by armish** [comment]
This looks amazing -- thanks for this amazing work, guys!
